import { chmod, mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { paths } from './paths';
import type { AppConfig, AppPreferences, TenantBrand } from './schema';
import { secretKeyForApp } from './schema';

const WINDOWS_PRIVATE_MODE = 0o500;
const POSIX_WRAPPER_MODE = 0o700;

export async function loadConfig(path: string = paths.configFile): Promise<Partial<AppConfig>> {
  try {
    const text = await readFile(path, 'utf8');
    return JSON.parse(text) as Partial<AppConfig>;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return {};
    throw err;
  }
}

/**
 * Atomic write: write to a sibling temp file with 0600 perms, then rename
 * (atomic on POSIX) into place. Avoids the partial-write window where a
 * crash could leave the config truncated, and keeps secret-bearing bytes
 * from ever existing at the final path with looser perms.
 */
/**
 * Build an AppConfig that points the app's secret at the encrypted local
 * keystore via an exec-provider SecretRef. Used by /account change and the
 * first-run migration path. Preserves the existing `preferences` block so
 * users don't lose unrelated settings on credential update.
 *
 * The provider command is a thin wrapper bridge writes under
 * `~/.lark-channel/secrets-getter[.cmd]` (always user-owned, never a symlink) so
 * lark-cli's AssertSecurePath audit accepts it regardless of how node was
 * installed (Homebrew / Volta / system pkg may put node behind a symlink
 * or root-own it). The wrapper internally `exec`s the real node + bridge
 * with `secrets get`. Bridge itself short-circuits the spawn and reads the
 * keystore directly when it sees its own wrapper path in `command`.
 */
export async function buildEncryptedAccountConfig(
  appId: string,
  tenant: TenantBrand,
  preferences?: AppPreferences,
): Promise<AppConfig> {
  const wrapperPath = await ensureSecretsGetterWrapper();
  return {
    accounts: {
      app: {
        id: appId,
        secret: {
          source: 'exec',
          provider: 'bridge',
          id: secretKeyForApp(appId),
        },
        tenant,
      },
    },
    secrets: {
      providers: {
        bridge: {
          source: 'exec',
          command: wrapperPath,
          // The wrapper has args baked in; pass none here.
          args: [],
        },
      },
    },
    ...(preferences ? { preferences } : {}),
  };
}

/**
 * Write (or rewrite) the secrets-getter wrapper to point at the currently-
 * running node + bridge entry script. Always rewrites — node path can move
 * between bridge runs (nvm version switch, re-install) and the wrapper
 * must stay in sync. Returns the wrapper path.
 *
 * On POSIX the wrapper is a `sh` script with 0700 perms. On Windows it's a
 * `.cmd` launcher marked read-only so lark-cli's secure-path audit doesn't
 * reject it as world-writable.
 */
export async function ensureSecretsGetterWrapper(): Promise<string> {
  const wrapperPath = paths.secretsGetterScript;
  const node = process.execPath;
  const bridgeEntry = process.argv[1] ?? '';
  const content =
    process.platform === 'win32'
      ? `@echo off\r\n` +
        `REM Auto-generated by lark-channel-bridge. Do not edit.\r\n` +
        `REM Forwards exec-provider requests to: node bridge secrets get\r\n` +
        `"${node}" "${bridgeEntry}" secrets get %*\r\n`
      : (() => {
          // Single-quoted shell-safe strings: escape any embedded single quotes.
          const sq = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`;
          return (
            `#!/bin/sh\n` +
            `# Auto-generated by lark-channel-bridge. Do not edit.\n` +
            `# Forwards exec-provider requests to: node bridge secrets get\n` +
            `exec ${sq(node)} ${sq(bridgeEntry)} secrets get "$@"\n`
          );
        })();

  await mkdir(dirname(wrapperPath), { recursive: true });
  const tmp = `${wrapperPath}.tmp-${process.pid}`;
  await writeFile(tmp, content, 'utf8');
  await chmod(tmp, process.platform === 'win32' ? WINDOWS_PRIVATE_MODE : POSIX_WRAPPER_MODE);
  if (process.platform === 'win32') {
    // A prior read-only wrapper cannot be atomically replaced on Windows.
    try {
      await chmod(wrapperPath, 0o600);
    } catch {}
    await rm(wrapperPath, { force: true });
  }
  await rename(tmp, wrapperPath);
  if (process.platform === 'win32') {
    await chmod(wrapperPath, WINDOWS_PRIVATE_MODE);
  }
  return wrapperPath;
}

export async function saveConfig(cfg: AppConfig, path: string = paths.configFile): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  const tmp = `${path}.tmp-${process.pid}`;
  await writeFile(tmp, `${JSON.stringify(cfg, null, 2)}\n`, 'utf8');
  // chmod the temp file before rename, so the destination path is never
  // visible with default permissions.
  await chmod(tmp, 0o600);
  await rename(tmp, path);
}
